routes/web.php
<?php

use App\Http\Controllers\CrateController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SupplierController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('products.index');
});

Route::get('suppliers/list', [SupplierController::class, 'getSuppliers'])->name('suppliers.list');
Route::get('products/list', [ProductController::class, 'getProducts'])->name('products.list');
Route::get('crates/list', [CrateController::class, 'getCrates'])->name('crates.list');

Route::resource('suppliers', SupplierController::class);
Route::resource('products', ProductController::class);
Route::resource('crates', CrateController::class);

app/Models/Crate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Crate extends Model
{
    use HasFactory;

    protected $fillable = [
        'discount'
    ];

    public function products()
    {
        return $this->belongsToMany(Product::class, 'crate_product', 'crates_id', 'products_id');
    }
}

app/Http/Controllers/CrateController.php
<?php

namespace App\Http\Controllers;

use App\Models\Crate;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Yajra\DataTables\DataTables;

class CrateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('crates.index');
    }

    public function getCrates(Request $request)
    {
        if ($request->ajax()) {
            $data = Crate::with('products')->orderBy('id')->get();
            return Datatables::of($data)
                ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $fruits = Product::all()->where('is_fruit');
        $vegetables = Product::all()->where('is_fruit', '=', 0);

        return view('crates.create', compact('fruits', 'vegetables'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws ValidationException
     */
    public function store(Request $request)
    {
        // replace NULL value of discount with 0
        if ($request->input('discount') == null) {
            $request->merge(['discount' => 0]);
        }
        $containsFruit = false;
        $products = Product::all()->whereIn('id', $request->input('products_id'))->sortBy('is_fruit');
        foreach ($products as $product) {
            if ($product->is_fruit) {
                $containsFruit = true;
                break;
            }
        }
        if (!$containsFruit) throw ValidationException::withMessages(['products_id' => 'At least 1 piece of fruit is required']);

        Crate::create($request->all())->products()->sync($request->input('products_id'), false);

        return redirect()->route('crates.index')
            ->with('success', 'Create was created.');
    }
}

resources/views/crates/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Crate</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('crates.index') }}" title="Back">Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('crates.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Discount (%):</strong>
                    <input type="number" class="form-control" name="discount"
                           placeholder="Discount" default="0" min="0" max="100" step="1">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label class="d-block" for="products">Products:</label>
                    <select id="products" name="products_id[]" multiple class="form-control">
                        <optgroup label="Fruit">
                            @foreach($fruits as $fruit)
                                <option value="{{ $fruit->id }}">{{ $fruit->title }}</option>
                            @endforeach
                        </optgroup>
                        <optgroup label="Vegetables">
                            @foreach($vegetables as $vegetable)
                                <option value="{{ $vegetable->id }}">{{ $vegetable->title }}</option>
                            @endforeach
                        </optgroup>
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/js/bootstrap-multiselect.min.js"
            integrity="sha512-ljeReA8Eplz6P7m1hwWa+XdPmhawNmo9I0/qyZANCCFvZ845anQE+35TuZl9+velym0TKanM2DXVLxSJLLpQWw=="
            crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/css/bootstrap-multiselect.min.css"
          integrity="sha512-wHTuOcR1pyFeyXVkwg3fhfK46QulKXkLq1kxcEEpjnAPv63B/R49bBqkJHLvoGFq6lvAEKlln2rE1JfIPeQ+iw=="
          crossorigin="anonymous"/>
    <script>
        $(document).ready(function () {
            $('#products').multiselect({
                nonSelectedText: 'Select Products',
                enableFiltering: true,
                enableCaseInsensitiveFiltering: true,
                buttonWidth: '100%',
                enableCollapsibleOptGroups: true,
            });
        });
    </script>
@endsection

resources/views/crates/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Crates</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('crates.create') }}" title="Create a crate"> New
                </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered table-responsive-lg" id="crates-table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Products</th>
            <th>Discount (%)</th>
            <th>Price After Discount</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>

    <script type="text/javascript">
        $(function () {
            let table = $('#crates-table').DataTable({
                processing: true,
                serverSide: true,
                searching: false,
                ordering: false,
                ajax: {
                    url: "{{ route('crates.list') }}"
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'products[, ].title', name: 'products'},
                    {data: 'discount', name: 'discount'},
                    {
                        data: function (row) {
                            let sum = 0;
                            for (const val of row.products) sum += val.price;
                            return Math.round((sum - sum * (row.discount / 100)) * 100) / 100;
                        }, name: 'total'
                    },
                ]
            });
        });
    </script>

@endsection