routes/web.php
<?php

use App\Http\Controllers\CrateController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SupplierController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('products.index');
});

Route::get('suppliers/list', [SupplierController::class, 'getSuppliers'])->name('suppliers.list');
Route::get('products/list', [ProductController::class, 'getProducts'])->name('products.list');
Route::get('crates/list', [CrateController::class, 'getCrates'])->name('crates.list');

Route::resource('suppliers', SupplierController::class);
Route::resource('products', ProductController::class);
Route::resource('crates', CrateController::class);

app/Models/Product.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';
    public $timestamps = true;

    protected $casts = [
        'price' => 'float'
    ];

    protected $fillable = [
        'title',
        'stock_count',
        'photo_path',
        'price',
        'suppliers_id',
        'is_fruit'
    ];

    public $sortable = [
        'id',
        'updated_at'
    ];

    public function supplier()
    {
        return $this->hasOne(Supplier::class, 'id', 'suppliers_id');
    }

    public function crates()
    {
        return $this->belongsToMany(Crate::class, 'crate_product', 'products_id', 'crates_id');
    }

    public function getUpdatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d.m.Y H:i:s');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Yajra\DataTables\DataTables;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('products.index');
    }

    public function getProducts(Request $request)
    {
        if ($request->ajax()) {
            $data = Product::with('supplier')->latest()->get();
            return Datatables::of($data)
                ->addColumn('action', function ($row) {
                    $actionButtons = '<a href="' . route('products.show', $row->id) . '" class="btn btn-secondary btn-sm">Show</a>';
                    $actionButtons .= '<a href="' . route('products.edit', $row->id) . '" class="edit btn btn-success btn-sm">Edit</a>';
                    $actionButtons .= '<form action="' . route('products.destroy', $row->id) . '" method="POST">' . method_field('DELETE') . csrf_field() . '<button class="btn btn-danger btn-sm">Delete</button></form>';
                    return $actionButtons;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $suppliers = DB::table('suppliers')->get();

        return view('products.create', compact('suppliers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'stock_count' => 'required',
            'price' => 'required',
            'suppliers_id' => 'required',
            'photo' => 'image|mimes:jpeg,jpg,png,gif,svg|max:2048'
        ]);

        if ($request->has('photo')) {
            // save the photo
            $image = $request->file('photo');
            $name = Str::slug($request->input('title')) . '_' . time();
            $filePath = '/image/' . $name . '.' . $image->getClientOriginalExtension();
            $image->storeAs('/image/', $name . '.' . $image->getClientOriginalExtension(), 'public');
        } else {
            $filePath = '/image/noimage.jpg';
        }

        $request->merge(['photo_path' => $filePath]);

        Product::create($request->all());

        return redirect()->route('products.index')
            ->with('success', 'Product created');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $suppliers = DB::table('suppliers')->get();

        return view('products.edit', compact('product', 'suppliers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'title' => 'required',
            'stock_count' => 'required',
            'price' => 'required',
            'suppliers_id' => 'required',
            'photo' => 'image|mimes:jpeg,jpg,png,gif,svg|max:2048'
        ]);

        if ($request->has('photo')) {
            // save the new photo and delete the old
            $image = $request->file('photo');
            $name = Str::slug($request->input('title')) . '_' . time();
            $filePath = '/image/' . $name . '.' . $image->getClientOriginalExtension();
            $image->storeAs('/image/', $name . '.' . $image->getClientOriginalExtension(), 'public');
            Storage::disk('public')->delete($product->photo_path);
            $request->merge(['photo_path' => $filePath]);
        }

        $product->update($request->all());

        return redirect()->route('products.index')
            ->with('success', 'Product updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        Storage::disk('public')->delete($product->photo_path);
        $product->delete();

        return redirect()->route('products.index')
            ->with('success', 'Product deleted');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}" title="Back">Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" class="form-control" placeholder="Title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Stock count:</strong>
                    <input type="number" step="1" min="0" class="form-control" name="stock_count"
                           placeholder="Stock count">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Photo:</strong>
                    <input type="file" name="photo" class="form-control" placeholder="Location">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price:</strong>
                    <input type="number" step="0.01" min="0" name="price" class="form-control" placeholder="Price">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Supplier:</strong>
                    <select name="suppliers_id" class="form-control">
                        @foreach($suppliers as $supplier)
                            <option value="{{ $supplier->id }}">{{ $supplier->title }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Is Fruit:</strong>
                    <input type="checkbox" name="is_fruit" value="1" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}" title="Go back">Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" value="{{ $product->title }}" class="form-control"
                           placeholder="Title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Stock count:</strong>
                    <input type="number" step="1" min="0" class="form-control" name="stock_count"
                           value="{{ $product->stock_count }}"
                           placeholder="Stock count">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Photo:</strong>
                    @if($product->photo_path)
                        <img src="{{ public_path('storage') . $product->photo_path }}" width="100px">
                    @endif
                    <input type="file" name="photo" class="form-control" placeholder="Location">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price:</strong>
                    <input type="number" step="0.01" min="0" name="price" value="{{ $product->price }}"
                           class="form-control" placeholder="Price">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Supplier:</strong>
                    <select name="suppliers_id" class="form-control">
                        @foreach($suppliers as $supplier)
                            <option
                                value="{{ $supplier->id }}" {{ $supplier->id != $product->suppliers_id ?: 'selected' }}>{{ $supplier->title }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Is Fruit:</strong>
                    <input type="checkbox" name="is_fruit" value="1"
                           {{ !$product->is_fruit ?: 'checked' }} class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Products</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('products.create') }}" title="Create a product">New</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="form-group">
        <label>In Stock:</label>
        <label for='stock-filter'></label><select id="stock-filter" class="form-control" style="width: 200px">
            <option value="">--</option>
            <option value="1">Yes</option>
            <option value="0">No</option>
        </select>
    </div>
    <table class="table table-bordered table-responsive-lg" id="products-table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Stock Count</th>
            <th>Price</th>
            <th>Photo</th>
            <th>Supplier</th>
            <th>Updated at</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>

    <script type="text/javascript">
        $(function () {
            var table = $('#products-table').DataTable({
                processing: true,
                serverSide: true,
                searchDelay: 350,
                ajax: {
                    url: "{{ route('products.list') }}"
                },
                columns: [
                    {data: 'id', name: 'id', orderable: true, searchable: true},
                    {data: 'title', name: 'title', orderable: false, searchable: true},
                    {data: 'stock_count', name: 'stock_count', orderable: false, searchable: true},
                    {data: 'price', name: 'price', orderable: false, searchable: false},
                    {
                        data: function (row) {
                            let path = '/storage/image/noimage.jpg';
                            if (row.photo_path) path = '/storage' + row.photo_path;
                            return '<img src="' + path + '" width="100px">'
                        }, name: 'photo_path', orderable: false, searchable: false
                    },
                    {data: 'supplier.title', name: 'supplier.title', orderable: false, searchable: true},
                    {data: 'updated_at', name: 'updated_at', orderable: true, searchable: false},
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });

            // in stock filtering
            $('#stock-filter').change(function () {
                if ($(this).val() === '') {
                    table.columns().search('').draw();
                }
                if ($(this).val() === '0') {
                    table.column(2)
                        .search('^[0]$', true)
                        .draw();
                }
                if ($(this).val() === '1') {
                    // stock count has to be greater than 0
                    table.column(2)
                        .search('^[1-9][0-9]*$', true)
                        .draw();
                }
            });
        });
    </script>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>  {{ $product->title }}</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}" title="Go back">Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $product->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Stock count:</strong>
                {{ $product->stock_count }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Photo:</strong>
                <img src="{{ $product->photo_path ? '/storage' . $product->photo_path : '/storage/image/noimage.jpg' }}"
                     width="100px">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price:</strong>
                {{ $product->price }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Supplier:</strong>
                {{ $product->supplier->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Date created:</strong>
                {{ date_format($product->created_at, 'd.m.Y h:m:s') }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Date updated:</strong>
                {{ $product->updated_at }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <strong>Crates with this product:</strong>
            <table class="table table-bordered table-responsive-lg">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Products</th>
                </tr>
                </thead>

                <tbody>
                @foreach($product->crates as $crate)
                    <tr>
                        <td>{{ $crate->id }}</td>
                        <td>@foreach($crate->products as $productInCrate)
                                {{ $productInCrate->title }}{{ ($loop->last ? '' : ',') }}
                            @endforeach
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection